// This file will be generated by running: pnpm supabase:types
// For now, this is a placeholder. Run the command after setting up Supabase.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          name: string | null
          bio: string | null
          avatar_url: string | null
          role: 'viewer' | 'creator' | 'moderator' | 'admin'
          role_scope: Json | null
          is_premium_creator: boolean
          public_profile_slug: string | null
          preferred_lang: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          bio?: string | null
          avatar_url?: string | null
          role?: 'viewer' | 'creator' | 'moderator' | 'admin'
          role_scope?: Json | null
          is_premium_creator?: boolean
          public_profile_slug?: string | null
          preferred_lang?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          bio?: string | null
          avatar_url?: string | null
          role?: 'viewer' | 'creator' | 'moderator' | 'admin'
          role_scope?: Json | null
          is_premium_creator?: boolean
          public_profile_slug?: string | null
          preferred_lang?: string
          created_at?: string
          updated_at?: string
        }
      }
      // Add other tables as needed...
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
